# Generated by Django 4.2 on 2025-10-23 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('professional_headline', models.CharField(max_length=200)),
                ('professional_summary', models.TextField(blank=True)),
                ('generated_summary', models.TextField(blank=True)),
                ('generated_cv_content', models.TextField(blank=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('cv_format', models.CharField(choices=[('HTML', 'HTML'), ('PDF', 'PDF'), ('DOCX', 'DOCX')], default='HTML', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('achievement', 'Achievement Example'), ('summary', 'Summary Example'), ('skill', 'Skill Description'), ('best_practice', 'Best Practice')], max_length=100)),
                ('role_type', models.CharField(choices=[('backend_developer', 'Backend Developer'), ('frontend_developer', 'Frontend Developer'), ('manager', 'Manager'), ('designer', 'Designer'), ('general', 'General')], default='general', max_length=100)),
                ('industry', models.CharField(default='general', max_length=100)),
                ('embedding_vector', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('job_description', models.TextField()),
                ('achievements', models.TextField()),
                ('technologies', models.TextField()),
                ('generated_bullets', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='cv_gen.cvdocument')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Soft', 'Soft Skill'), ('Language', 'Language'), ('Certification', 'Certification')], max_length=50)),
                ('proficiency_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_gen.cvdocument')),
            ],
            options={
                'ordering': ['category', 'skill_name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=200)),
                ('graduation_date', models.DateField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('honors', models.CharField(blank=True, max_length=200)),
                ('relevant_coursework', models.TextField(blank=True)),
                ('generated_section', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='cv_gen.cvdocument')),
            ],
            options={
                'ordering': ['-graduation_date'],
            },
        ),
    ]
