# Generated by Django 5.2 on 2025-10-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='generated_professional_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='generated_cv_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='generated_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='generated_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='generated_bullets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
