# Generated by Django 5.2 on 2025-10-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_gen', '0002_add_rag_fields'),
        ('cv_gen', '0002_cvdocument_generated_at_and_more'),
    ]

    operations = [
    ]
