# Generated by Django 5.2 on 2025-10-24 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_gen', '0003_merge_20251024_0310'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={},
        ),
        migrations.RenameIndex(
            model_name='knowledgebase',
            new_name='cv_gen_know_profess_9fcbda_idx',
            old_name='cv_gen_know_profes_cv_sec_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgebase',
            new_name='cv_gen_know_profess_5a38ff_idx',
            old_name='cv_gen_know_profes_categ_idx',
        ),
        migrations.RemoveField(
            model_name='cvdocument',
            name='cv_format',
        ),
        migrations.RemoveField(
            model_name='cvdocument',
            name='generated_professional_summary',
        ),
        migrations.RemoveField(
            model_name='education',
            name='generated_section',
        ),
        migrations.RemoveField(
            model_name='education',
            name='relevant_coursework',
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='generated_description',
            field=models.TextField(blank=True, help_text='AI-generated education description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='generated_description',
            field=models.TextField(blank=True, help_text='AI-generated job description'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='generated_cv_content',
            field=models.JSONField(blank=True, default=dict, help_text='Complete generated CV content'),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='generated_summary',
            field=models.TextField(blank=True, help_text='AI-generated professional summary'),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='profession',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('Accounts Payable Specialist', 'Accounts Payable Specialist'), ('Financial Analyst', 'Financial Analyst'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('DevOps Engineer', 'DevOps Engineer'), ('Data Scientist', 'Data Scientist'), ('Data Engineer', 'Data Engineer'), ('Manager', 'Manager'), ('Project Manager', 'Project Manager'), ('Product Manager', 'Product Manager'), ('QA Engineer', 'QA Engineer'), ('Systems Administrator', 'Systems Administrator'), ('Network Engineer', 'Network Engineer'), ('Security Engineer', 'Security Engineer'), ('Cloud Architect', 'Cloud Architect'), ('Software Architect', 'Software Architect'), ('Business Analyst', 'Business Analyst'), ('UX/UI Designer', 'UX/UI Designer'), ('Marketing Manager', 'Marketing Manager'), ('Sales Manager', 'Sales Manager'), ('HR Manager', 'HR Manager'), ('General', 'General')], db_index=True, default='General', help_text="User's profession for targeted RAG retrieval", max_length=100),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='professional_headline',
            field=models.CharField(help_text='e.g., Senior Backend Developer', max_length=255),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cvgenerationfeedback',
            name='feedback_text',
            field=models.TextField(blank=True, help_text='Optional user feedback/comments'),
        ),
        migrations.AlterField(
            model_name='cvgenerationfeedback',
            name='generated_content',
            field=models.TextField(help_text='The generated content being rated'),
        ),
        migrations.AlterField(
            model_name='cvgenerationfeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐ Poor'), (2, '⭐⭐ Fair'), (3, '⭐⭐⭐ Good'), (4, '⭐⭐⭐⭐ Very Good'), (5, '⭐⭐⭐⭐⭐ Excellent')], help_text="User's rating 1-5"),
        ),
        migrations.AlterField(
            model_name='cvgenerationfeedback',
            name='section_type',
            field=models.CharField(choices=[('summary', 'Professional Summary'), ('experience', 'Experience Description'), ('achievement', 'Achievement Bullet'), ('responsibility', 'Job Responsibility'), ('skill', 'Skill'), ('education', 'Education'), ('certification', 'Certification'), ('award', 'Award/Recognition'), ('project', 'Project Description')], help_text='Which section the feedback is about', max_length=50),
        ),
        migrations.AlterField(
            model_name='cvgenerationfeedback',
            name='suggested_improvement',
            field=models.TextField(blank=True, help_text='What could be improved?'),
        ),
        migrations.AlterField(
            model_name='cvgenerationfeedback',
            name='was_helpful',
            field=models.BooleanField(default=True, help_text='Did user find this helpful?'),
        ),
        migrations.AlterField(
            model_name='education',
            name='cv_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv_gen.cvdocument'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='honors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='category',
            field=models.CharField(db_index=True, help_text='General category', max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='confidence_score',
            field=models.FloatField(default=1.0, help_text='Confidence score (0-1) for this entry'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content',
            field=models.TextField(help_text='Full content of the KB entry'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content_type',
            field=models.CharField(choices=[('bullet', 'Single Bullet Point'), ('paragraph', 'Full Paragraph'), ('job_description', 'Complete Job Description'), ('achievement', 'Achievement Statement')], default='bullet', help_text='Type of content (bullet, paragraph, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='cv_section',
            field=models.CharField(choices=[('summary', 'Professional Summary'), ('experience', 'Experience Description'), ('achievement', 'Achievement Bullet'), ('responsibility', 'Job Responsibility'), ('skill', 'Skill'), ('education', 'Education'), ('certification', 'Certification'), ('award', 'Award/Recognition'), ('project', 'Project Description')], db_index=True, default='achievement', help_text='Which CV section this applies to', max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='embedding_vector',
            field=models.TextField(help_text='384-dimensional embedding vector (JSON format)'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='industry',
            field=models.CharField(blank=True, db_index=True, help_text='Industry/sector', max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='profession',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('Accounts Payable Specialist', 'Accounts Payable Specialist'), ('Financial Analyst', 'Financial Analyst'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('DevOps Engineer', 'DevOps Engineer'), ('Data Scientist', 'Data Scientist'), ('Data Engineer', 'Data Engineer'), ('Manager', 'Manager'), ('Project Manager', 'Project Manager'), ('Product Manager', 'Product Manager'), ('QA Engineer', 'QA Engineer'), ('Systems Administrator', 'Systems Administrator'), ('Network Engineer', 'Network Engineer'), ('Security Engineer', 'Security Engineer'), ('Cloud Architect', 'Cloud Architect'), ('Software Architect', 'Software Architect'), ('Business Analyst', 'Business Analyst'), ('UX/UI Designer', 'UX/UI Designer'), ('Marketing Manager', 'Marketing Manager'), ('Sales Manager', 'Sales Manager'), ('HR Manager', 'HR Manager'), ('General', 'General')], db_index=True, default='General', help_text='Target profession for this entry', max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='role_type',
            field=models.CharField(db_index=True, help_text='Type of role', max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='source_document',
            field=models.CharField(blank=True, help_text='Source PDF or document', max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='title',
            field=models.CharField(help_text='Title/heading of the KB entry', max_length=300),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Number of words in content'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='generated_bullets',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated achievement bullets'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='technologies',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['cv_section', 'category'], name='cv_gen_know_cv_sect_15c5c7_idx'),
        ),
    ]
